#!/bin/bash
#   ____            _                _     _
#  / ___| ___ _ __ | |_ ___   ___   | |   (_)_ __  _   ___  __
# | |  _ / _ \ '_ \| __/ _ \ / _ \  | |   | | '_ \| | | \ \/ /
# | |_| |  __/ | | | || (_) | (_) | | |___| | | | | |_| |>  <
#  \____|\___|_| |_|\__\___/ \___/  |_____|_|_| |_|\__,_/_/\_\
#
#  ___           _        _ _
# |_ _|_ __  ___| |_ __ _| | | ___ _ __
#  | || '_ \/ __| __/ _` | | |/ _ \ '__|  Author: Kitae Kim
#  | || | | \__ \ || (_| | | |  __/ |     Email:  kitaekim27 at gmail.com
# |___|_| |_|___/\__\__,_|_|_|\___|_|     Desc:   A shell script for automating
#                                                 installation of Gentoo Linux.
#

set -o errexit -o nounset -o noglob -o pipefail

info() {
	echo "${THIS_SCRIPT}:" "${@}"
}

error() {
	info "${@}" >&2
}

get_passphrase() {
	local checkphrase
	while true
	do
		read -srp "${1}" "${2}"; echo
		read -srp "Enter the passphrase again: " checkphrase; echo
		[ "$(eval echo "\$${2}")" = "${checkphrase}" ] && break
		info "You've entered different passphrases! Try again."
	done
}

main_check_network() {
	if ! nc -zw1 google.com 443
	then
		error "Can not connect to the internet!"
		exit 1
	fi
}

main_prepare_installer() {
	info "Sync the installer time with ntp.org."
	ntpd -q -g

	info "Install the scripts into the installer."
	find -L "${THIS_DIR}/tools" -mindepth 1 -maxdepth 1 \
		-exec cp --recursive {} /usr/local/bin \;

	info "Install tpm2-tools in the installer."
	${EMERGE} --autounmask --autounmask-continue app-crypt/tpm2-tools

	info "Configure Portage mirrors."
	PORTAGE_MIRRORS=$(mirrorselect --interactive --output)
	echo "${PORTAGE_MIRRORS}" >> /etc/portage/make.conf
}

main_prepare_storage() {
	lsblk
	read -rp "Select a root storage: " ROOT_STORAGE
	fdisk "/dev/${ROOT_STORAGE}"
	sync

	lsblk
	read -rp "Select an efi partition: " PARTITION_UEFI
	read -rp "Select a swap partition: " PARTITION_SWAP
	read -rp "Select a root partition: " PARTITION_ROOT
}

main_configure_storage() {
	info "Format an efi partition in vfat."
	mkfs.vfat "/dev/${PARTITION_UEFI}"

	info "Set swap on ${PARTITION_SWAP}."
	mkswap "/dev/${PARTITION_SWAP}"
	swapon "/dev/${PARTITION_SWAP}"

	info "Seal a random key into TPM."
	tpmsealrandkey

	info "Create a LUKS2 passphrase for the root partition."
	local passphrase
	get_passphrase "Enter a passphrase for the root partition: " passphrase
	local luksphrase=$(mkpassphrase "${passphrase}" | sed "s/result = \(.*\)/\1/")

	info "Encrypt the root partition."
	echo "${luksphrase}" | xxd -revert -plain | cryptsetup luksFormat \
		--type="luks2" --key-file="-" "/dev/${PARTITION_ROOT}"

	info "Add a secondary passphrase for the root partition."
	get_passphrase "Enter a secondary passphrase for the root partition: " secondphrase
	echo "${luksphrase}" | xxd -revert -plain | cryptsetup luksAddKey \
		--key-file="-" "/dev/${PARTITION_ROOT}" \
		<(printf "%s" "${secondphrase}")

	info "Decrypt the root partition for further installation."
	echo "${luksphrase}" | xxd -revert -plain | cryptsetup luksOpen \
		--key-file="-" "/dev/${PARTITION_ROOT}" root

	info "Format the root partition in btrfs."
	mkfs.btrfs /dev/mapper/root

	info "Mount the root partition."
	mkdir --parents /mnt/root
	mount /dev/mapper/root /mnt/root

	info "Set the filesystem hierarchy layout in the root partition."
	mkdir --parents /mnt/root/boot
	mkdir --parents /mnt/root/deploy
	mkdir --parents /mnt/root/snapshots

	info "Create a btrfs subvolume to install the system."
	# Here, note that our initial subvolume is image-a.
	btrfs subvolume create /mnt/root/deploy/image-a
	ln --symbolic /deploy/image-a /mnt/root/deploy/target
	ln --symbolic /deploy/none /mnt/root/deploy/current
	# This makes mounttab valid so that we can see / mount entry inside the
	# chroot.
	mount --types="btrfs" --options="subvol=/deploy/target" \
		/dev/mapper/root /mnt/root/deploy/image-a

	INSTALL_ROOT="/mnt/root/deploy/image-a"
}

main_install_stage3() {
	# TODO: Verify the downloaded files.
	info "Download a stage 3 tarball."
	local arch="amd64"
	local mirror="http://ftp.kaist.ac.kr/gentoo/releases"
	wget --recursive --no-parent --no-directories \
		--directory-prefix="download" \
		--accept="stage3-${arch}-hardened-openrc-*.tar.xz" \
		"${mirror}/${arch}/autobuilds/current-stage3-${arch}-openrc/"

	info "Extract the stage 3 tarball into ${INSTALL_ROOT}."
	find "${THIS_DIR}/download" -iname "stage3-*.tar.xz" \
		-exec tar --directory="${INSTALL_ROOT}" \
			--extract --preserve-permissions --file={} \
			--xattrs-include='*.*' --numeric-owner \;
}

main_prepare_chroot() {
	info "Mount pseudo filesystems in the installation."
	mount-pseudofs "${INSTALL_ROOT}"

	info "Configure DNS of the installation."
	cp --dereference /etc/resolv.conf "${INSTALL_ROOT}/etc/resolv.conf"

	info "Set the initramfs source directory in the installation."
	mkdir --parents "${INSTALL_ROOT}/var/lib/initramfs"
	find "${THIS_DIR}/initramfs" -mindepth 1 -maxdepth 1 \
		-exec cp --archive {} "${INSTALL_ROOT}/var/lib/initramfs" \;

	info "Copy config files into the installation."
	cp --verbose --recursive "${THIS_DIR}/config" "${INSTALL_ROOT}"

	info "Install my scripts into the installation."
	find -L "${THIS_DIR}/tools" -mindepth 1 -maxdepth 1 \
		-exec cp --verbose --recursive {} "${INSTALL_ROOT}/usr/local/bin/" \;
}

chroot_cleanup() {
	info "Clean up installation artiparcts."
	rm --recursive /config
}

chroot_main() {
	info "Mount an efi partition."
	mount "/dev/${PARTITION_UEFI}" /boot

	info "Mount the portage build directory as a tmpfs."
	mkdir --parents /var/tmp/portage
	mount --types="tmpfs" --options="noatime,nosuid,nodev" tmpfs /var/tmp/portage

	info "Install Portage environment config files."
	mkdir --parents /etc/portage/env
	find /config/etc/portage/env -type f -exec cp {} /etc/portage/env \;

	info "Generate the fstab into the installation."
	PARTUUID_UEFI=$(blkid -o value -s PARTUUID "/dev/${PARTITION_UEFI}") \
	PARTUUID_SWAP=$(blkid -o value -s PARTUUID "/dev/${PARTITION_SWAP}") \
	PARTUUID_ROOT=$(blkid -o value -s PARTUUID "/dev/${PARTITION_ROOT}") \
		envsubst < /config/etc/fstab.tmpl > /etc/fstab

	if [ -d /etc/portage/package.use ]
	then
		info "Make the Portage package.use a single file."
		rm --recursive /etc/portage/package.use
		touch /etc/portage/package.use
	fi

	info "Configure the Portage make.conf file."
	install --mode="600" /config/etc/portage/make.conf /etc/portage/make.conf
	echo "MAKEOPTS=\"-j$(nproc)\"" >> /etc/portage/make.conf

	info "Configure the Portage ebuild repositories."
	mkdir --parents /etc/portage/repos.conf
	cp /usr/share/portage/config/repos.conf /etc/portage/repos.conf/gentoo.conf
	emerge-webrsync

	emerge="nice --12 emerge --quiet-build"

	info "Install system management tools."
	${EMERGE} app-portage/gentoolkit sys-fs/btrfs-progs

	info "Set the system-wide USE flags."
	euse --enable minimal elogind X bluetooth networkmanager dbus \
		dist-kernel
	euse --disable systemd

	info "Configure Portage mirrors."
	echo "${PORTAGE_MIRRORS}" >> /etc/portage/make.conf

	info "Choose a Portage profile."
	eselect profile list
	read -rp "Select a Portage profile: " profile
	eselect profile set "${profile}"

	info "Update @world Portage set."
	# Here, we use `--jobs="$(nproc)"` flag which may cause memory
	# exhaustion. The assumptions are as we will use a bare minimum profile,
	# we don't have any packages consume memory drastcally such as a desktop
	# environment and the @world set usually contain many packages that
	# actually does not build anything but just setting up the system.
	${EMERGE} --jobs="$(nproc)" --update --deep --newuse @world

	info "Set the timezone to Asia/Seoul."
	echo "Asia/Seoul" > /etc/timezone
	${EMERGE} --config sys-libs/timezone-data

	info "Generate system locales."
	nano /etc/locale.gen
	locale-gen

	info "Configure system locales."
	eselect locale list
	read -rp "Select a locale: " locale
	eselect locale set "${locale}"

	info "Reload the environment."
	env-update
	source /etc/profile

	if grep --quiet --ignore-case "AMD" /proc/cpuinfo
	then
		info "AMD CPU detected. Install AMD microcodes."
		# AMD microcodes are shipped in the sys-kernel/linux-firmware package.
		info "Enable USE flag \"initramfs\" of sys-kernel/linux-firmware"
		echo "sys-kernel/linux-firmware initramfs" >> /etc/portage/package.use
	elif grep --quiet --ignore-case "Intel" /proc/cpuinfo
	then
		info "Intel CPU detected. Install Intel microcodes."
		info "Enable USE flag \"initramfs\" of sys-firmware/intel-microcode"
		# This USE flag generates microcode cpio at /boot so that GRUB automatically
		# detect and generate config with it.
		echo "sys-firmware/intel-microcode initramfs" >> /etc/portage/package.use

		info "Install the intel microcode package."
		${EMERGE} sys-firmware/intel-microcode
	else
		info "Can not determine CPU manufacturer. Do not install microcodes."
	fi

	info "Install the linux firmwares."
	echo "sys-kernel/linux-firmware linux-fw-redistributable no-source-code" \
		>> /etc/portage/package.license
	${EMERGE} sys-kernel/linux-firmware

	info "Install the linux kernel."
	echo "sys-kernel/gentoo-kernel-bin hardened" >> /etc/portage/package.use
	${EMERGE} sys-kernel/gentoo-kernel-bin

	# /usr/src/linux symlink refers to the source tree corresponding to the
	# currently running kernel.
	info "Create a symlink /usr/src/linux."
	eselect kernel list
	read -rp "Select a linux kernel to use: " kernel
	eselect kernel set "${kernel}"

	info "Install fzf to build an initramfs."
	${EMERGE} app-shells/fzf

	info "Download Alpine Linux rootfs to build an initramfs."
	arch="x86_64"
	mirror="https://dl-cdn.alpinelinux.org"
	wget --recursive --no-parent --no-directories --no-verbose \
		--directory-prefix="/var/lib/initramfs" \
		--accept-regex="alpine-minirootfs-[0-9.]*-${arch}.tar.gz$" \
		"${mirror}/alpine/latest-stable/releases/${arch}/"

	info "Build and install an initramfs."
	mkalpineinitfs

	info "Set the hostname."
	read -rp "Enter the hostname: " hostname
	sed -i "s/localhost/${hostname}/g" /etc/conf.d/hostname /etc/hosts

	info "Enable the elogind service."
	rc-update add elogind boot

	info "Install system daemons."
	${EMERGE} sys-process/fcron net-misc/chrony net-misc/networkmanager \
		app-admin/rsyslog

	info "Register system daemons to openrc runlevels."
	rc-update add fcron default
	rc-update add chronyd default
	rc-update add NetworkManager default
	rc-update add rsyslog default

	info "Install system packages."
	${EMERGE} app-admin/doas
	install --mode="600" config/etc/doas.conf /etc/doas.conf
	echo "app-admin/logrotate cron" >> /etc/portage/package.use
	${EMERGE} app-admin/logrotate

	info "Install GRUB2 bootloader."
	${EMERGE} sys-boot/grub
	grub-install --efi-directory="/boot" --removable
	echo "GRUB_CMDLINE_LINUX=\"root=PARTUUID=$(blkid -o value -s PARTUUID /dev/"${PARTITION_ROOT}")\"" \
		>> /etc/default/grub
	grub-mkconfig --output="/boot/grub/grub.cfg"

	info "Create a default user."
	read -rp "Enter an user name: " user
	useradd --create-home --groups="users,wheel" --shell="/bin/bash" "${user}"
	passwd "${user}"
	install --mode="644" /config/home/user/dot-profile "/home/${user}/.profile"

	info "Install XOrg server."
	${EMERGE} x11-base/xorg-server
	env-update
	source /etc/profile
}

main() {
	main_check_network
	main_prepare_installer
	main_prepare_storage
	main_configure_storage
	main_install_stage3
	main_prepare_chroot
	info "chroot into ${INSTALL_ROOT} and execute chroot_main()."
	chroot "${INSTALL_ROOT}" /bin/bash -c "
		set -o errexit -o nounset -o noglob -o pipefail
		THIS_SCRIPT=${THIS_SCRIPT}
		ROOT_STORAGE=${ROOT_STORAGE}
		PARTITION_UEFI=${PARTITION_UEFI}
		PARTITION_SWAP=${PARTITION_SWAP}
		PARTITION_ROOT=${PARTITION_ROOT}
		PORTAGE_MIRRORS=${PORTAGE_MIRRORS}
		EMERGE=${EMERGE}
		$(declare -f info)
		$(declare -f error)
		$(declare -f chroot_cleanup)
		$(declare -f chroot_main)
		chroot_main
		chroot_cleanup
	"
}

if [ "${EUID}" != 0 ]
then
	error "This script requires root privilege!"
	exit 1
fi

THIS_SCRIPT=$(basename "${BASH_SOURCE[0]}")
THIS_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

ROOT_STORAGE=""
PARTITION_UEFI=""
PARTITION_SWAP=""
PARTITION_ROOT=""

INSTALL_ROOT=""
PORTAGE_MIRRORS=""

readonly EMERGE="nice --12 emerge --quiet-build"

main "${@}"
