#!/bin/bash
# Load the given snapshot.

set -o errexit -o nounset -o noglob -o pipefail

info() {
    echo "$(basename "$0"):" "$@"
}

error() {
    info "$@" >&2
}

if [ "$EUID" != 0 ]
then
    error "This script requires root privilege."
    exit 1
fi

readonly snapshot="$1"

if [ ! -e "/host-rootfs/snapshots/${snapshot}" ]
then
    error "The given snapshot ${snapshot} does not exist!"
fi

if [ "$(readlink -f /host-rootfs/deploy/current)" = "image-a" ]
then
    next_image="image-b"
else
    next_image="image-a"
fi

info "Load a snapshot ${snapshot} as ${next_image}."

btrfs subvolume snapshot \
    "/host-rootfs/snapshots/${snapshot}" \
    "/host-rootfs/deploy/${next_image}"

rm /host-rootfs/deploy/target
ln --symbolic --force "${next_image}" /host-rootfs/deploy/target

info "Done."
