#!/bin/bash
# Load the given snapshot.

set -o errexit -o nounset -o noglob -o pipefail

info() {
	echo "$(basename "${0}"):" "${@}"
}

error() {
	info "${@}" >&2
}

if [ "${EUID}" != 0 ]
then
	error "This script requires root privilege."
	exit 1
fi

readonly snapshot="${1}"

if [ ! -e "/snapshots/${snapshot}" ]
then
	error "The given snapshot ${snapshot} does not exist!"
	exit 1
fi

if [ "$(readlink -f /deploy/current)" = "/image-a" ]
then
	next_image="/image-b"
else
	next_image="/image-a"
fi

info "Load a snapshot ${snapshot} as ${next_image}."

btrfs subvolume snapshot "/snapshots/${snapshot}" "/${next_image}"

rm /rootvolume/deploy/target
ln --symbolic "/deploy/${next_image}" /rootvolume/deploy/target

info "Done."
