#!/bin/bash
# Load the given snapshot.

set -o errexit -o nounset -o noglob -o pipefail

info() {
	echo "$(basename "${0}"):" "${@}"
}

error() {
	info "${@}" >&2
}

if [ "${EUID}" != 0 ]
then
	error "This script requires root privilege."
	exit 1
fi

readonly snapshot="${1}"

if [ ! -e "/rootvolume/snapshots/${snapshot}" ]
then
	error "The given snapshot ${snapshot} does not exist!"
fi

if [ "$(readlink -f /rootvolume/deploy/current)" = "image-a" ]
then
	next_image="image-b"
else
	next_image="image-a"
fi

info "Load a snapshot ${snapshot} as ${next_image}."

btrfs subvolume snapshot \
	"/rootvolume/snapshots/${snapshot}" \
	"/rootvolume/deploy/${next_image}"

rm /rootvolume/deploy/target
ln --symbolic --force "/deploy/${next_image}" /rootvolume/deploy/target

info "Done."
