#!/bin/bash
# Sanely find and print a location of the given executable.
# `which` prints some weird strings (e.g. "ls: aliased to ls --color=tty")
path=$(whereis -b "${1?}" | awk '{print $2}')
# `whereis` returns 0 even if it can't find any path.
[ -z "${path}" ] && exit 1
echo "${path}"
