#!/bin/bash

set -o errexit -o nounset -o noglob -o pipefail

if [ "${EUID}" != 0 ]
then
	echo "This script requires root privilege!" >&2
	exit 1
fi

git -C /usr/src/dwm fetch origin release
git -C /usr/src/dwm reset --hard origin/release
make --directory="/usr/src/dwm" --jobs="$(nproc)" clean install
