#!/bin/bash
# Build and install an initramfs.
#
# Note that this script expects that `/usr/src/initramfs` directory contains all
# the necessary files.
#
# This script does not copy any firmware and modules into the initramfs.
# If you're willing to copy them, copy files in /lib/firmware and /lib/modules.

set -o errexit -o nounset -o noglob -o pipefail

info() {
    echo "$(basename "$0"):" "$@"
}

error() {
    info "$@" >&2
}

if [ "$EUID" != 0 ]
then
    error "This script requires root privilege!"
    exit 1
fi

initramfs_source="/usr/src/initramfs"
initramfs_buiddir=$(mktemp --directory)

linux_version=$(lslinux | fzf --header="Select the target linux kernel version.")

info "Copy files in the source directory into the build directory."
find "$initramfs_source" -mindepth 1 -maxdepth 1 \
    -exec cp --recursive --preserve --no-dereference {} "$initramfs_buiddir" \;

info "Copy my scripts into the initramfs build directory."
cp "$(which mkpassphrase)" "$initramfs_buiddir/usr/local/bin"

info "Install the busybox into the initramfs build directory."
rcopy "$(which busybox)" "$initramfs_buiddir"
chroot "$initramfs_buiddir" /bin/busybox --install -s

info "Install the tpm2-tools into the initramfs build directory."
rcopy "$(which tpm2)" "$initramfs_buiddir"

info "Install the cryptsetup into the initramfs build directory."
rcopy "$(which cryptsetup)" "$initramfs_buiddir"

info "Build and install the initramfs into /boot."
( cd "$initramfs_buiddir" && find . -mindepth 1 -print0 \
    | cpio --null --create --format="newc" \
    | lz4 --to-stdout > "/boot/initrd.img-$linux_version" )
