#!/bin/sh
# Concatenate the key in TPM and the given passphrase to generate a new passphrase.
set -o errexit -o nounset -o noglob -o pipefail

PASSPHRASE="${1}"
TPM_KEY="${2}"
TMPDIR=$(mktemp -d)

DIGEST_KEY=$(printf "%s" "${TPM_KEY}" | base64 -d | sha256sum | awk '{print $1}')
DIGEST_PHRASE=$(printf "%s" "${PASSPHRASE}" | sha256sum | awk '{print $1}')
DIEGST_CONCAT="${DIGEST_KEY}${DIGEST_PHRASE}"

printf "%s" "${DIEGST_CONCAT}" | hex2data | sha256sum | awk '{print "result =", $1}'
