#!/bin/bash
# Create a snapshot of the running root filesystem.

set -o errexit -o nounset -o noglob -o pipefail

info() {
	echo "$(basename "${0}"):" "${@}"
}

error() {
	info "${@}" >&2
}

if [ "${EUID}" != 0 ]
then
	error "This script requires root privilege!"
	exit 1
fi

snapshot=$(date -Iseconds)

info "Create a snapshot ${snapshot}."

# Make a read-only snapshot of currently running root filesystem in the
# `/rootvolume/snapshots` directory.
btrfs subvolume snapshot -r / "/snapshots/${snapshot}"

info "Done."
