#!/bin/sh
set -o errexit -o nounset -o noglob -o pipefail

cleanup() {
	rm -r "${TMPDIR}"
}

TMPDIR=$(mktemp -d)
trap cleanup EXIT

# Unseal the key from the first non-reserved persistent object handle (0x81018000).
tpm2 startauthsession --policy-session --session="${TMPDIR}/session.bin"
tpm2 policypcr --quiet --session="${TMPDIR}/session.bin" --pcr-list="sha256:0,2,4,8,9"
tpm2 unseal --auth="session:${TMPDIR}/session.bin" --object-context="0x81018000" | base64
